run:
  timeout: 5m
  tests: false
  skip-dirs:
    - client/v2/common
  
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - exportloopref
    - gci
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nolintlint
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/algorand)
      - prefix(github.com/algorand/go-algorand-sdk)

    section-separators:
      - newLine

severity:
  default-severity: error

issues:
  # Currently checks lint errors that were committed after v2.1
  new-from-rev: e85d1961c86009482306497313a2e0fea5bc3dbd

  # Disable default exclude rules listed in `golangci-lint run --help` (selectively re-enable some below)
  exclude-use-default: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  exclude:
    # ignore govet false positive fixed in https://github.com/golang/go/issues/45043
    - "sigchanyzer: misuse of unbuffered os.Signal channel as argument to signal.Notify"
    # ignore golint false positive fixed in https://github.com/golang/lint/pull/487
    - "exported method (.*).Unwrap` should have comment or be unexported"
    # ignore issues about the way we use _struct fields to define encoding settings
    - "`_struct` is unused"

    # Enable some golangci-lint default exception rules:
    # "EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok"
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    # "EXC0005 staticcheck: Developers tend to write in C-style with an explicit 'break' in a 'switch', so it's ok to ignore"
    - ineffective break statement. Did you mean to break out of the outer loop
